spring:
  application:
    name: ai-code-generator
server:
  port: 8101
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.tlj.aicodegenerator.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
